# Generated by Django 2.0b1 on 2018-06-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_sales',
            field=models.IntegerField(default=0),
        ),
    ]
